/*
 * This file is generated by jOOQ.
*/
package sages.bootcamp.tracker.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import sages.bootcamp.tracker.jooq.tables.Projects;
import sages.bootcamp.tracker.jooq.tables.Tasks;
import sages.bootcamp.tracker.jooq.tables.UserProject;
import sages.bootcamp.tracker.jooq.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1689984669;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.projects</code>.
     */
    public final Projects PROJECTS = sages.bootcamp.tracker.jooq.tables.Projects.PROJECTS;

    /**
     * The table <code>public.tasks</code>.
     */
    public final Tasks TASKS = sages.bootcamp.tracker.jooq.tables.Tasks.TASKS;

    /**
     * The table <code>public.user_project</code>.
     */
    public final UserProject USER_PROJECT = sages.bootcamp.tracker.jooq.tables.UserProject.USER_PROJECT;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = sages.bootcamp.tracker.jooq.tables.Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.PROJECTS_ID_SEQ,
            Sequences.TASKS_ID_SEQ,
            Sequences.USERS_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Projects.PROJECTS,
            Tasks.TASKS,
            UserProject.USER_PROJECT,
            Users.USERS);
    }
}
