/*
 * This file is generated by jOOQ.
*/
package sages.bootcamp.tracker.jooq;


import javax.annotation.Generated;

import sages.bootcamp.tracker.jooq.tables.Projects;
import sages.bootcamp.tracker.jooq.tables.Tasks;
import sages.bootcamp.tracker.jooq.tables.UserProject;
import sages.bootcamp.tracker.jooq.tables.Users;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.projects</code>.
     */
    public static final Projects PROJECTS = sages.bootcamp.tracker.jooq.tables.Projects.PROJECTS;

    /**
     * The table <code>public.tasks</code>.
     */
    public static final Tasks TASKS = sages.bootcamp.tracker.jooq.tables.Tasks.TASKS;

    /**
     * The table <code>public.user_project</code>.
     */
    public static final UserProject USER_PROJECT = sages.bootcamp.tracker.jooq.tables.UserProject.USER_PROJECT;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = sages.bootcamp.tracker.jooq.tables.Users.USERS;
}
